apiVersion: v1
kind: Service
metadata:
  name: {{ include "metube.fullname" . }}
  namespace: {{ .Values.namespace | default $.Release.Namespace }}
  labels:
    {{- include "metube.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metube.selectorLabels" . | nindent 4 }}
