replicaCount: 1
namespace: ""

envVars:
  usePing: 'true'
  relativeUrl: '/'
  quickWizard: 'false'
  isHassio: 'false'
  disableHaAuth: 'true'

image:
  repository: ghcr.io/esphome/esphome
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

initContainers: []

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
#  runAsUser: 0
#  runAsGroup: 0

securityContext: {}
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

revisionHistoryLimit: 3

service:
  labels: {}
  annotations: {}
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "2"
    memory: 2G
  requests:
    cpu: "0.1"
    memory: 100Mi

livenessProbe:
  httpGet:
    port: 6052
    path: /version
    httpHeaders:
      - name: User-Agent
        value: HealthCheck

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
additionalVolumes: []

configVolumeMount:
  name: "config"
  mountPath: "/config"


# Additional volumeMounts on the output Deployment definition.
additionalVolumeMounts: []

configVolumeClaim:
  # Creates volume claim with {esphome.fullname}-config name
  create: true
  size: 5Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

nodeSelector: {}

tolerations: []

affinity: {}
